image: alpine/edge
packages:
  - rsync
  - deno
  - git-cliff
environment:
  deploy: tim@vps.tukler.no
  dir: filmpolitiet-api
  source: git@git.sr.ht:~timharek/filmpolitiet-api
secrets:
  - 0323bc6f-a046-4b96-8496-2bac6e7ee107
sources:
  - https://git@git.sr.ht/~timharek/filmpolitiet-api
triggers:
  - action: email
    condition: failure
    to: tim@harek.no
tasks:
  - test: |
      cd $dir
      deno task check
      deno test -A
  - mirror: |
      cd $dir
      git remote add github git@github.com:timharek/filmpolitiet-api.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git push github main
      if [ "$(git describe --exact-match --tags HEAD)" ]; then \
        git push --tags github; \
      fi
  - update_changelog: |
      cd $dir
      if ! [ "$(git describe --exact-match --tags HEAD)" ]; then \
        complete-build; \
      fi
      git checkout main
      git cliff -o CHANGELOG.md
      git add CHANGELOG.md
      git commit -m "chore(release): Update CHANGELOG"
      git push -o skip-ci
  - set_srht_defaults: |
      cd $dir
      ssh-keyscan -t rsa git.sr.ht >> ~/.ssh/known_hosts
      git remote set-url origin $source
  - deploy: |
      cd $dir
      git --no-pager log -1 --format=%ci > last_deploy
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avrP --exclude "last_deploy" . $deploy:/var/www/filmpolitiet.wyd.no
      rsync --rsh="$sshopts" -avrP last_deploy $deploy:/var/www/filmpolitiet.wyd.no/last_deploy
