image: alpine/edge
packages:
  - rsync
  - deno
environment:
  deploy: tim@vps.tukler.no
  dir: filmpolitiet-api
secrets:
  - 0323bc6f-a046-4b96-8496-2bac6e7ee107
sources:
  - https://git@git.sr.ht/~timharek/filmpolitiet-api
triggers:
  - action: email
    condition: failure
    to: tim@harek.no
tasks:
  - test: |
      cd $dir
      deno task check
      deno test -A
  - mirror: |
      cd $dir
      git remote add github git@github.com:timharek/filmpolitiet-api.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git push github main
      if [ "$(git describe --exact-match --tags HEAD)" ]; then \
        git push --tags github; \
      fi
  - deploy: |
      if ! [ "$(git describe --exact-match --tags HEAD)" ]; then \
        complete-build; \
      fi
      cd $dir
      git --no-pager log -1 --format=%ci > last_deploy
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avrP --exclude "last_deploy" . $deploy:/var/www/filmpolitiet.wyd.no
      rsync --rsh="$sshopts" -avrP last_deploy $deploy:/var/www/filmpolitiet.wyd.no/last_deploy
