image: alpine/edge
packages:
  - rsync
  - deno
  - git-cliff
environment:
  deploy: tim@vps.tukler.no
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
secrets:
  - 0323bc6f-a046-4b96-8496-2bac6e7ee107
sources:
  - https://git@git.sr.ht/~timharek/filmpolitiet-api
triggers:
  - action: email
    condition: failure
    to: tim@harek.no
tasks:
  - setup: |
      echo 'cd filmpolitiet-api' >> ~/.buildenv
  - test: |
      deno task check
      deno task test
  - mirror: |
      git push --force --mirror git@github.com:timharek/filmpolitiet-api.git
  - check_release: |
      tag=$(git describe --exact-match --tags HEAD 2>/dev/null || true)
      if [ -z "$tag" ]; then
        echo "Current commit is not a tag: not a new release"
        complete-build
      fi
  - update_changelog: |
      git checkout main
      git cliff -o CHANGELOG.md
      git add CHANGELOG.md
      git commit -m "chore(release): Update CHANGELOG"
      git push -o skip-ci
  - deploy: |
      git --no-pager log -1 --format=%ci > last_deploy
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avrP --exclude "last_deploy" . $deploy:/var/www/filmpolitiet.wyd.no
      rsync --rsh="$sshopts" -avrP last_deploy $deploy:/var/www/filmpolitiet.wyd.no/last_deploy
