// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_scrape_index from "./routes/api/scrape/index.ts";
import * as $api_scrape_rss from "./routes/api/scrape/rss.ts";
import * as $docs from "./routes/docs.tsx";
import * as $entries from "./routes/entries.tsx";
import * as $index from "./routes/index.tsx";
import * as $reviewers from "./routes/reviewers.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_app.tsx": $_app,
    "./routes/api/scrape/index.ts": $api_scrape_index,
    "./routes/api/scrape/rss.ts": $api_scrape_rss,
    "./routes/docs.tsx": $docs,
    "./routes/entries.tsx": $entries,
    "./routes/index.tsx": $index,
    "./routes/reviewers.tsx": $reviewers,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
